### ISSUE TITLE
Getting Error: Cannot find module './near-seed-phrase'

### ISSUE THREAD

**Issue by inventionarts** [zavodil/near-api-server#3]
Hi. 

Believe I got everything installed per directions, but cannot find this near-seed-phrase when running `node app.` which presumably starts the server. 

I did find a folder here called near-seed-phrase and copied that into the near-api-server folder. But running `near app` then produces errors where it cannot find any of the requires in index.js:
const bip39 = require('bip39-light');
const { derivePath } = require('near-hd-key');
const bs58 = require('bs58');
const nacl = require('tweetnacl');

Not sure where to find this seedphrase module or where to place it once I have it (I assumed could be in the directory where I am attempting to get the API server going so I can try minting NFTs as shown, etc.

Here's the error:

Error: Cannot find module './near-seed-phrase'
Require stack:
- /Users/ronmartinez/near1/near-api-server/user.js
- /Users/ronmartinez/near1/near-api-server/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/ronmartinez/near1/near-api-server/user.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ronmartinez/near1/near-api-server/user.js',
    '/Users/ronmartinez/near1/near-api-server/app.js'
  ]

Thanks! Eager to make this work!

Ron

**Comment by zavodil** [comment]
Hey could you try to run `npm i near-seed-phrase` from the project folder please? Re https://www.npmjs.com/package/near-seed-phrase

**Comment by inventionarts** [comment]
Thank you. Got it, and it now appears in node_modules and seems to be loading. But now I'm getting Cannot find module 'faker'  (in app.js).

Note: the readme says to set up the accounts and so on in config.js but believe the file for this is settings.js, no? Thanks for your help!

**Comment by zavodil** [comment]
Did you run `npm install` from the project folder? It should install dependencies

**Comment by inventionarts** [comment]
Re-ran npm install from the folder and it seems to have solved the problem. Server is running. Thanks!
